spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/email-dispatcher
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

email-dispatcher:
  config:
    kafka:
      topic-name: local-topic
      email-key: email